### ISSUE TITLE
How to automatically update current playing music info ?

### ISSUE THREAD

**Issue by xsahil03x** [boyan01/flutter-music-player#1]
In the example, we are showing the current position and all other information of the currently playing music. But they get updated only when the music changes or when we play pause it.

How to make this thing automatic so that we can see the latest current position.

**Comment by boyan01** [comment]
well, `PlaybackState` has a field named `lastPositionUpdateTime`

https://github.com/boyan01/flutter-music-player/blob/820889fa3baddfce31cc2bbf3643e2e847b9648a/lib/src/model/playback_state.dart#L87

so, you can get real position for current time.

```dart
// calculate the delay
PlaybackState state = getState();
int diff = DateTime.now().millisecondsSinceEpoch - state.lastPositionUpdateTime;

// this would be the value what you want.
int position =  state.position + diff;
```

**Comment by xsahil03x** [comment]
No, you are getting it wrong. My question is that we are already listening to `MusicPlayer` in `PlayerWidget` class and calling `setState()`, Then why the current metadata of music is not updating regularly? It only updates when we play/pause or changes the music.

Like if I have a seek bar in which I want to show the current playing music progress, but it is not working as expected. It only gets updated when I change the music state. 

Any help would be appreciated. Thank You

**Comment by boyan01** [comment]
Actually, it doesn't need update the `PlaybackState` for a simple progress update. 
there are two reason :

1.  We already got all information what we need.
2. `PlaybackState`'s updating will affect all widget which is listening `MusicPlayer`, therefore the cost of starting a timer to continually loop and update progress is expensive.

If you want to monitor the playback progress in one `Widget`，just schedule a `Timer` to update **this widget** repeatedly.

**Comment by xsahil03x** [comment]
Thanks,  totally got your point.
