### ISSUE TITLE
有点迷惘，不明白怎么做

### ISSUE THREAD

**Issue by lylelqc** [boyan01/flutter-music-player#19]
大佬，这个是分别调了Android和iOS的底层方法吗，一直想搞懂如何实现，又不知道怎么下手

**Comment by boyan01** [comment]
简单介绍一下实现方式吧：

**分别用Kotlin / Swift 写一个 Android / iOS 上的音乐播放器，然后 Dart 通过 `MethodChannel`控制平台上的播放器来进行播放操作**

这是 dart 中播放器控制的 channel: 
https://github.com/boyan01/flutter-music-player/blob/8663cb010d48c5b4ef0df1d83741f2957bea8ea0/lib/src/channel_ui.dart#L13

**Comment by lylelqc** [comment]
感谢大佬指点，还有这个playerBackgroundService，不知道怎么实现后台播放，大佬能解答一下吗

**Comment by xibici** [comment]
大佬 我在我项目集成了但是ios可以用 安卓显示create service出错  没看过kotlin看不懂 怎么办

**Comment by boyan01** [comment]
> 我在我项目集成了但是ios可以用 安卓显示create service出错 没看过kotlin看不懂 怎么办

可以提 Issue。

附上机型，环境，log 日志等信息，我可以协助看看。

另外，这个项目不建议用于生成环境哈。需要完善的地方还有很多。

**Comment by boyan01** [comment]
有啥其他的问题可以开其他的 Issues， 这个我暂时先关闭了哈。

**Comment by xibici** [comment]
貌似没事了 早上不行 不知道为什么晚上居然可以了

**Comment by boyan01** [comment]
> 貌似没事了 早上不行 不知道为什么晚上居然可以了

可能是这个提交 https://github.com/boyan01/flutter-music-player/commit/8b6c839bb774570e0cc7107d5205b1f31ce52bfb 起作用了...

**Comment by xibici** [comment]
原来如此 谢谢大佬
