### ISSUE TITLE
system_clock.h not found

### ISSUE THREAD

**Issue by StenpZ** [boyan01/flutter-music-player#28]
build Error：system_clock.h not found。
var append = state == PlayerState.Playing ? (SystemClock.uptime().inMilliseconds - updateTime) : 0;   
===>
var append = state == PlayerState.Playing ? (DateTime.now().millisecondsSinceEpoch - updateTime) : 0;
这里为什么不用这种方式呢？

**Comment by boyan01** [comment]
`DateTime.now().millisecondsSinceEpoch`  拿到到的时间戳取决于设备系统设置中的时间。

用户前往设置中修改时间，容易导致播放进度出现问题。

**Comment by boyan01** [comment]
https://github.com/boyan01/system_clock/issues/1
