### ISSUE TITLE
Lyrics no scroll

### ISSUE THREAD

**Issue by vickyvu0684** [boyan01/flutter-music-player#29]
Dear admin,
 I 've tried  on IOS 13.1.5 but lyrics no scroll. 

please help me

* Updated:
I replaced  

`var append = state == PlayerState.Playing ? (SystemClock.uptime().inMilliseconds - updateTime) : 0;`

with

`var append = state == PlayerState.Playing ? (DateTime.now().millisecondsSinceEpoch - updateTime) : 0 ;`

It's ok now. I dont know why that.

**Comment by vickyvu0684** [comment]
> Dear admin,
> I 've tried on IOS 13.1.5 but lyrics no scroll.
> 
> please help me

**Comment by boyan01** [comment]
Hi, sorry for delay. 

This is a bug because the implementation on the iOS platform and the implementation on the Dart side use different time APIs, resulting in inconsistent time acquisitions.

solution would be like this:
```dart

  int get computedPosition {
    int now;
    if (Platform.isIos) {
      now =  DateTime.now().millisecondsSinceEpoch;
    } else {
      now = SystemClock.uptime().inMilliseconds;
    }
    var append = state == PlayerState.Playing ? (now  - updateTime) : 0;
    append = (append * speed).toInt();
    return position + append;
  }

```
