### ISSUE TITLE
support for ios

### ISSUE THREAD

**Issue by bardiarastin** [boyan01/flutter-music-player#4]
Hi, thanks so much for the time you're putting on this, I wanted to know that is there any plan for ios support?!

**Comment by boyan01** [comment]
A few days ago, I tried using Swift to implement ios playback. However, in the process of implementation, I was confused and felt that my understanding of the MediaSession framework was incorrect, so I am currently re-planning and redesigning the API of library.

here is the branch of ios development：
https://github.com/boyan01/flutter-music-player/tree/dev

**Comment by boyan01** [comment]
in a short.  I have a plan, but not now.

**Comment by bardiarastin** [comment]
I guess taking a look at this repo can help you a little bit on implementing ios side if you need a mac device I can give you access to my own with Team Viewer or something else just feel free to contact me on a.rastin98@gmail.com or https://t.me/bardiarastin
https://github.com/react-native-kit/react-native-track-player

**Comment by boyan01** [comment]
Maybe I can learn or extend the platform code from this repo.

I already have a mac, thank you for your help.

**Comment by bardiarastin** [comment]
so much thanks for your work ❤️

**Comment by bardiarastin** [comment]
@boyan01 any progress on this?
