### ISSUE TITLE
Define ticket and boards or milestone  (IOS platform) 

### ISSUE THREAD

**Issue by phuongphally** [boyan01/flutter-music-player#5]
Can you define milestone and ticket list then, I will pick up it and working with you? 

I'm so interested in your project  and I don't know to build it my self, But I know some of swfit knowledge and  ios. 

If you have times please help define what we should do then I do it with you.

Thanks @boyan01 .

**Comment by boyan01** [comment]
Sorry for delay. 

Thank you very much for being willing to help and willing to participate in this project.  

welcome to join this project , I could set you up as a collaborator if you want.

 in addition, if you do not know how to build this project, you can just ask me or open an issue.

**Comment by boyan01** [comment]
in short, there are three milestones：

1.  support simple playback in IOS
2.  support background playback
3.  support playback URL Interception from Dart.
4.  others you want add it.

**Comment by phuongphally** [comment]
@boyan01  Why you separate `player-service` and  `play-back-controller` channels?

**Comment by boyan01** [comment]
`channel` is a bridge which connected  flutter (dart) and native (java/swift) . when application into background , the flutter view would be destroyed. 

**what we need is continue playing even application go to background.**

so i separate it.

**Comment by phuongphally** [comment]
Yes Thanks 

Why you did not create one channel instead of two-channel? 

-> `play` ( playing music and push notification controller same times )

-> 'stop'   (stop the music and remove notification controller same times)

**Comment by boyan01** [comment]
* Channel "tech.soit.quiet/player" : `player`

control the player 

* Channel "tech.soit.quiet/background_callback": `background_callback`

in Android, when app entry background, the foreground view can be destroy by system anytime.  so if I want support playback URL Interception. it is needed to define another channel for this case.

**Comment by xsahil03x** [comment]
You can also have a look at https://github.com/ryanheise/audio_service, the package is working in both IOS and android

**Comment by phuongphally** [comment]
Thanks for @boyan01  you did it. 

But why can not play 

   `mediaId` 
 `mediaUri`  remote URL (http://facebook.com/file.mp3)


````
 MusicMetadata(
    title: "Zhu Lin Jian",
    subtitle: "Zhu Lin Jian - SanWu marblue",
    mediaId: "12345",
    mediaUri: "http://facebook.com/file.mp3",
    iconUri: "https://via.placeholder.com/150/FFCA28/000000/?text=bamboo",
  ),

````

Or how to use it? 


Thanks

**Comment by boyan01** [comment]
In iOS and new Android versions, http plaintext requests are disabled by
default.

 you can try with https urls.

Phuong Phally (ភួង ផល្លី) <notifications@github.com> 于 2020年3月2日周一 00:13写道：

**Comment by phuongphally** [comment]
@boyan01  Thanks. 

I have another question is 

How can I set player-service to `default to loop(shift)`

**Comment by boyan01** [comment]
@phuongphally  Do you mean the play mode of the playlist? the default is sequence with loop

**Comment by phuongphally** [comment]
Yes. Can I do it?
