### ISSUE TITLE
无法播放网络资源，只能播放本地

### ISSUE THREAD

**Issue by lxykad** [boyan01/flutter-music-player#6]

**Comment by boyan01** [comment]
播放网络资源报什么错误？

**Comment by lxykad** [comment]
> 播放网络资源报什么错误？
> 
> What error is reported when playing network resources?

http://music.163.com/song/media/outer/url?id=28737747.mp3   demo里的本地音频随便替换成网络的资源都会报错，播放不了，log为com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://music.163.com/song/media/outer/url?id=28737747.mp3
E/ExoPlayerImplInternal(20292): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
E/ExoPlayerImplInternal(20292): 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
E/ExoPlayerImplInternal(20292): 	at tech.soit.quiet.utils.UrlUpdatingDataSource.open(MediaSource.kt:121)
E/ExoPlayerImplInternal(20292): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(20292): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal(20292): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(20292): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/ExoPlayerImplInternal(20292): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
E/ExoPlayerImplInternal(20292): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(20292): 	at java.lang.Thread.run(Thread.java:784)
E/ExoPlayerImplInternal(20292): Caused by: java.io.IOException: Cleartext HTTP traffic to music.163.com not permitted
E/ExoPlayerImplInternal(20292): 	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
E/ExoPlayerImplInternal(20292): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
E/ExoPlayerImplInternal(20292): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
E/ExoPlayerImplInternal(20292): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:528)

**Comment by boyan01** [comment]
```
Caused by: java.io.IOException: Cleartext HTTP traffic to music.163.com not permitted
```

Android 9 默认禁用了 HTTP 协议，可以使用低于 28 的设备播放试试。

**Comment by lxykad** [comment]
> Caused by: java.io.IOException: Cleartext HTTP traffic



> ```
> Caused by: java.io.IOException: Cleartext HTTP traffic to music.163.com not permitted
> ```
> 
> Android 9 默认禁用了 HTTP 协议，可以使用低于 28 的设备播放试试。

柜子类翻出来个5.1的设备，确实可以了。不过28之后不解决，没法玩啊

**Comment by lxykad** [comment]
> ```
> Caused by: java.io.IOException: Cleartext HTTP traffic to music.163.com not permitted
> ```
> 
> Android 9 默认禁用了 HTTP 协议，可以使用低于 28 的设备播放试试。

com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302
E/ExoPlayerImplInternal( 6725): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
E/ExoPlayerImplInternal( 6725): 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
E/ExoPlayerImplInternal( 6725): 	at tech.soit.quiet.utils.UrlUpdatingDataSource.open(MediaSource.kt:121)
E/ExoPlayerImplInternal( 6725): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 6725): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal( 6725): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal( 6725): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/ExoPlayerImplInternal( 6725): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/ExoPlayerImplInternal( 6725): 	at java.lang.Thread.run(Thread.java:831)

也不是在低版本设备上所有的链接都可以播，比如这个  https://music.163.com/song/media/outer/url?id=1397021895.mp3

**Comment by boyan01** [comment]
> 柜子类翻出来个5.1的设备，确实可以了。不过28之后不解决，没法玩啊

Android 9 之后不建议再使用 HTTP 协议明文传输。具体开启方法自己检索。

> 也不是在低版本设备上所有的链接都可以播，比如这个 https://music.163.com/song/media/outer/url?id=1397021895.mp3

目前看是 ExoPlayer 未对服务端 302 响应码做处理导致无法播放。

**Comment by lxykad** [comment]
> > 柜子类翻出来个5.1的设备，确实可以了。不过28之后不解决，没法玩啊
> 
> Android 9 之后不建议再使用 HTTP 协议明文传输。具体开启方法自己检索。
> 
> > 也不是在低版本设备上所有的链接都可以播，比如这个 https://music.163.com/song/media/outer/url?id=1397021895.mp3
> 
> 目前看是 ExoPlayer 未对服务端 302 响应码做处理导致无法播放。



> > 柜子类翻出来个5.1的设备，确实可以了。不过28之后不解决，没法玩啊
> 
> Android 9 之后不建议再使用 HTTP 协议明文传输。具体开启方法自己检索。
> 
> > 也不是在低版本设备上所有的链接都可以播，比如这个 https://music.163.com/song/media/outer/url?id=1397021895.mp3
> 
> 目前看是 ExoPlayer 未对服务端 302 响应码做处理导致无法播放。

已解决，多谢啦
